### ISSUE TITLE
missing the HUB stack update procedure description from version v3.0.0 to v3.0.1

### ISSUE THREAD

**Issue by jwiechmann** [aws-solutions/network-orchestration-for-aws-transit-gateway#53]
**What were you initially searching for in the docs?**
We updated the HUB stack well from v2 to v3.0.0. The documentation was helping for that. But with the new version v3.0.1 we are missing the update description. I guess it's the same procedure like the SPOKE stack: "Choose Update, then choose Replace current template."

**Is this related to an existing part of the documentation? Please share a link**
https://docs.aws.amazon.com/solutions/latest/serverless-transit-network-orchestrator/update-the-stack.html
https://github.com/aws-solutions/serverless-transit-network-orchestrator/releases

**Describe how we could make it clearer**
A separate description would be helpful to update from v3.0.0 to v3.0.1.
It would also be important to have a notice of the bridge name change: "STNO-EventBridge-v3" perhaps in the release documentation.

**If you have a proposed update, please share it here**

**Comment by tbelmega** [comment]
Hi,
we do not describe the update path for every release.
Usually all you have to do is update the stack with the new template.
The update to v3.0.0 was a special case, because there were breaking changes that needed to be mitigated manually. That's what we documented in the implementation guide.

When there is no description for a certain version upgrade in the documentation of any solution, the update is as simple as updating the stack with the new template.
