### ISSUE TITLE
Using Customizations for Control Tower to Deploy newest STNO v3

### ISSUE THREAD

**Issue by khhonard-aws** [aws-solutions/network-orchestration-for-aws-transit-gateway#58]
Hello team,

Hopefully looking to get an answer for this soon. I'm consistently getting errors with my CodePipeline for Customizations for Control Tower (CfCT) to deploy this new solution for STNO. The error that I'm getting from CloudFormation:

"ResourceLogicalId:TgwPeeringLambda, ResourceType:AWS::Lambda::Function, ResourceStatusReason:Properties validation failed for resource TgwPeeringLambda with message: #/Code/S3Bucket: failed validation constraint for keyword [pattern]."

There are no parameters that I've configured for this particular resource. I'm really out of guesses how to fix this error. Could someone help me fix this problem?

Screenshot:
![Screen Shot 2022-08-08 at 8 14 26 PM](https://user-images.githubusercontent.com/70538701/183555881-cb84fef6-f998-4689-86b0-9c354f40e148.png)

**Comment by tbelmega** [comment]
Hi @khhonard-aws ,
what is your CodePipeline supposed to do, build the solution from this GitHub project and then deploy it?

I'm guessing, because the error message hints at 'TgwPeeringLambda/Properties/Code/S3Bucket', and that is reading a mapping value. The mapping value is defined as 
```
Mappings:
  SourceCode:
    General:
      S3Bucket: "%DIST_BUCKET_NAME%"
```
which is invalid and would produce that error message, if you tried to deploy this template with CloudFormation directly.

The [README](https://github.com/aws-solutions/serverless-transit-network-orchestrator/blob/main/README.md#build) explains how you prepare the template for deployment.
Apologies in case you're already following the instructions from the README.

**Comment by tbelmega** [comment]
No response, closing

**Comment by randyspainhower** [comment]
> Hello team,
> 
> Hopefully looking to get an answer for this soon. I'm consistently getting errors with my CodePipeline for Customizations for Control Tower (CfCT) to deploy this new solution for STNO. The error that I'm getting from CloudFormation:
> 
> "ResourceLogicalId:TgwPeeringLambda, ResourceType:AWS::Lambda::Function, ResourceStatusReason:Properties validation failed for resource TgwPeeringLambda with message: #/Code/S3Bucket: failed validation constraint for keyword [pattern]."
> 
> There are no parameters that I've configured for this particular resource. I'm really out of guesses how to fix this error. Could someone help me fix this problem?
> 
> Screenshot: ![Screen Shot 2022-08-08 at 8 14 26 PM](https://user-images.githubusercontent.com/70538701/183555881-cb84fef6-f998-4689-86b0-9c354f40e148.png)

Did you ever get a resolution to this? We have our stno in customizations for control tower as well (As deployed by AWS Proserve engagemenet) and i'm curious about upgrading in that pipeline....  I don't understand why AWS was pushing to use this in that pipeline but then not explaining how to upgrade in that path....
